/*
 *  Version: 1.0
 *
 *  The contents of this file are subject to the OpenVPMS License Version
 *  1.0 (the 'License'); you may not use this file except in compliance with
 *  the License. You may obtain a copy of the License at
 *  http://www.openvpms.org/license/
 *
 *  Software distributed under the License is distributed on an 'AS IS' basis,
 *  WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 *  for the specific language governing rights and limitations under the
 *  License.
 *
 *  Copyright 2006 (C) OpenVPMS Ltd. All Rights Reserved.
 *
 *  $Id$
 */

package org.openvpms.web.component.im.print;

import org.openvpms.component.business.domain.im.common.Entity;
import org.openvpms.component.business.domain.im.common.IMObject;
import org.openvpms.component.business.domain.im.document.Document;
import org.openvpms.component.business.domain.im.party.Party;
import org.openvpms.component.business.service.archetype.ArchetypeServiceException;
import org.openvpms.component.business.service.archetype.ArchetypeServiceHelper;
import org.openvpms.component.business.service.archetype.IArchetypeService;
import org.openvpms.component.system.common.exception.OpenVPMSException;
import org.openvpms.report.DocFormats;
import org.openvpms.report.IMObjectReport;
import org.openvpms.report.IMObjectReportException;
import org.openvpms.report.IMObjectReportFactory;
import org.openvpms.report.PrintProperties;
import org.openvpms.report.TemplateHelper;
import org.openvpms.web.component.app.GlobalContext;
import org.openvpms.web.system.ServiceHelper;

import java.util.ArrayList;
import java.util.List;


/**
 * Prints reports for {@link IMObject}s generated by {@link IMObjectReport}.
 *
 * @author <a href="mailto:support@openvpms.org">OpenVPMS Team</a>
 * @version $LastChangedDate: 2006-05-02 05:16:31Z $
 */
public class IMObjectReportPrinter<T extends IMObject>
        extends AbstractIMObjectPrinter<T> {

    /**
     * Constructs a new <code>IMObjectReportPrinter</code>.
     *
     * @param object the object to print
     */
    public IMObjectReportPrinter(T object) {
        super(object);
    }

    /**
     * Returns a document for an object.
     *
     * @return a document
     * @throws IMObjectReportException   for any report error
     * @throws ArchetypeServiceException for any archetype service error
     */
    public Document getDocument() {
        List<IMObject> objects = new ArrayList<IMObject>();
        objects.add(getObject());
        IMObjectReport report = createReport();
        String[] mimeTypes = {DocFormats.PDF_TYPE};
        return report.generate(objects, mimeTypes);
    }

    /**
     * Returns the default printer for an object.
     *
     * @return the default printer, or <code>null</code> if there is
     *         none defined
     * @throws OpenVPMSException for any error
     */
    public String getDefaultPrinter() {
        String printer = null;
        String shortName = getObject().getArchetypeId().getShortName();
        Entity template = TemplateHelper.getTemplateForArchetype(
                shortName, ArchetypeServiceHelper.getArchetypeService());
        Party practice = GlobalContext.getInstance().getPractice();
        if (template != null && practice != null) {
            IArchetypeService service
                    = ArchetypeServiceHelper.getArchetypeService();
            printer = TemplateHelper.getPrinter(template, practice, service);
        }
        return printer;
    }

    /**
     * Creates a new report.
     *
     * @return a new report
     * @throws IMObjectReportException   for any report error
     * @throws ArchetypeServiceException for any archetype service error
     */
    protected IMObjectReport createReport() {
        String shortName = getObject().getArchetypeId().getShortName();
        return IMObjectReportFactory.create(
                shortName, ArchetypeServiceHelper.getArchetypeService(),
                ServiceHelper.getDocumentHandlers());
    }

    /**
     * Returns the print properties for an object.
     *
     * @param object  the object to print
     * @param printer the printer
     * @return the print properties
     * @throws OpenVPMSException for any error
     */
    @Override
    protected PrintProperties getProperties(T object, String printer) {
        PrintProperties properties = super.getProperties(object, printer);
        String shortName = object.getArchetypeId().getShortName();
        Entity template = TemplateHelper.getTemplateForArchetype(
                shortName, ArchetypeServiceHelper.getArchetypeService());
        if (template != null) {
            properties.setMediaSize(getMediaSize(template));
            properties.setMediaTray(getMediaTray(template, printer));
        }

        return properties;
    }
}
